channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.11.9
  - scrapy=2.11
  - python-dotenv=1.0
  - pillow=10.3
  - pip:
    - azure-ai-formrecognizer==3.3.*
    - azureml-core==1.56.*
    - azure-storage-blob==12.20.*
    - pymupdf==1.24.*
    - matplotlib==3.9.1
    - openai==1.35.*
